export const ACTIONS = {
    SET_LANGUAGE:"SET_LANGUAGE",
    SET_USER:"SET_USER",
    REMOVE_USER:"REMOVE_USER",
    SET_SAVED_LISTS:"SET_SAVED_LISTS",
    SET_SAVE_LIST:"SET_SAVE_LIST",
    SET_SETTINGS:"SET_SETTINGS"
}